TB-obj-parser
TRIQS/FermiSee pull request #2
Opened 2022-07-07 22:30 UTC by srahim457

Added the json store function to the tools
There is a radio button object in the Hamiltonian tab that switches between uploading w90 or the uploading of pythTB.
load_data.py can parse the json and make a triqs lattice object.

2022-07-08 20:28 UTC, srahim457 commented
added the save_json.py to tools

2022-07-12 13:56 UTC, the-hampel approved these changes

2022-07-12 14:37 UTC, the-hampel requested changes

2022-07-12 14:37 UTC, the-hampel commented on load_data.py
> +        t = i[0]
This has to be fixed first. There can be off diagonal terms in the hoppings. Meaning that we have to store for each hopping a matrix norb x norb.

2022-07-18 19:07 UTC, the-hampel approved these changes

2022-07-22 15:31 UTC, the-hampel commented on tabs/tab1_callbacks.py
> +        print(k_mesh['k_points_dash'])
remove debug print out

2022-08-10 22:04 UTC, the-hampel commented on tabs/tab1_callbacks.py
> +        print(csv_string)
rm debug prin

2022-08-10 22:04 UTC, the-hampel commented on tabs/tab1_callbacks.py
> +        #plot_data = list(zip(k_mesh['k_disc'],*tb_data['eps_nuk']))
rm debug stuf

2022-08-10 22:04 UTC, the-hampel commented on tabs/tab1_layout.py
> +                #html.H3('A(k,ω)', id=id('Akw-title'), style={'textAlign': 'center'}),
can be removed

2022-08-10 22:06 UTC, the-hampel commented on load_data.py
> +    print(site_energies)
rm debug print

2022-08-10 22:06 UTC, the-hampel commented on load_data.py
> +            print(hop)
rm debug print

2022-08-12 21:48 UTC, phibeck commented on tools/calc_tb.py
> +import solid_dmft.postprocessing as sdmft
Please remove both lines.

2022-08-12 21:48 UTC, phibeck commented on tools/calc_tb.py
> +            #print(total_proj)
Please remove last line.

2022-08-12 21:48 UTC, phibeck commented on tabs/tab2_callbacks.py
> +            #tb_kslice_data['eps_nuk'], evec_nuk = tb.get_tb_kslice(tbl, k_mesh, dft_mu)
remove last line

2022-08-12 21:48 UTC, phibeck commented on tabs/dashboard.py
> +                                          placeholder='select orbitals Ex: 0,1,2'),
remove "select orbitals" (it's already written explicitly.

2022-08-12 21:48 UTC, phibeck commented on tools/calc_akw.py
> +    print(eps_min, eps_max)
Remove last line.

2022-08-15 13:52 UTC, phibeck approved these changes

2022-08-16 20:18 UTC, the-hampel approved these changes

2022-08-16 20:36 UTC, phibeck approved these changes

2022-08-16 20:46 UTC, phibeck approved these changes

2022-08-16 20:48 UTC, merged